# Generated by Django 3.2 on 2022-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_and_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('party_size', models.IntegerField(default=1)),
                ('additional', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
            ],
        ),
    ]
