# Generated by Django 3.2 on 2022-01-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0002_auto_20220106_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
