# Generated by Django 3.2 on 2022-01-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0004_auto_20220106_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='party',
            new_name='booker',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_and_date',
            field=models.DateTimeField(default=None),
        ),
    ]
