# Generated by Django 3.2 on 2022-01-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0006_auto_20220106_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='seats',
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
