# Generated by Django 3.2 on 2022-01-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0010_auto_20220116_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
    ]
