# Generated by Django 3.2 on 2022-02-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0016_auto_20220208_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='min_people',
        ),
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
